- name: copy files for Debian's family 
  ansible.builtin.template:
    src: ~/Ansible/roles/web_service/templates/server1.conf.j2
    dest: /etc/apache2/sites-available/server1.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Ubuntu"

- name: copy files for RHEL's family site
  ansible.builtin.template:
    src: ~/Ansible/roles/web_service/templates/server2.conf.j2
    dest: /etc/httpd/conf.d/server2.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Rocky"

- name: copy folder for RHEL's family site
  ansible.builtin.copy:
    src: ~/Ansible/roles/web_service/files/info.php
    dest: /var/www/{{ domain }}/
    owner: root
    group: root

