- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: latest

- name: starts service, if not started
  tags: always
  ansible.builtin.service:
    name: nginx
    state: started
